### ISSUE TITLE
breaker: URL structure changed with new Bold theme

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#43] opened 2024-11-12 15:37 UTC
Old URL structure had dates:

https://readsludge.com/2024/11/08/trump-selects-corporate-lobbyist-susie-wiles-as-chief-of-staff/

New theme doesn't:

https://readsludge.com/trump-selects-corporate-lobbyist-susie-wiles-as-chief-of-staff/

Roll back, or fix in Code Injection?

cc @donnysludge

**Comment by unitof** [comment] 2024-11-12 16:06
Caused by upload of new routes.yaml file, fixed by merging back that permalink line

**Closed by unitof** 2024-11-12 16:06 UTC
